Revert "use a symlink instead of copy of the file"
This reverts commit a9325a3180eea20cf2a9148cab84e3e9c5fcb540.

Test kitchen complains the file doesn't exist:

ERROR: Errno::ENOENT: No such file or directory - /tmp/apache2/../apache2/test/kitchen/cookbooks/apache2_test/files/default/tests/minitest/support/helpers.rb